# Generated by Django 2.0.7 on 2019-06-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='Product name'),
        ),
    ]
